# Generated by Django 5.1.6 on 2025-03-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can_view'), ('can_create', 'can_view'), ('can_edit', 'can_view'), ('can_delete', 'can_view')]},
        ),
    ]
