# Generated by Django 5.1.6 on 2025-02-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autour',
            new_name='Author',
        ),
    ]
