# Generated by Django 5.1.6 on 2025-02-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
