# Generated by Django 5.1.6 on 2025-02-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
    ]
